config/routes.rb
Rails.application.routes.draw do
get 'top/login_form'
post 'top/login'
get 'top/logout'
resources :tweets
resources :users
root 'tweets#index'
resources :likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
    
    
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users,through: :likes,source: :user
    validates :message,presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :like_tweets,through: :likes ,source: :tweet
    
    validates :uid,presence: true,uniqueness: :true
    validates :pass,presence: true
    
    def self.autenticate(uid,pass)
        user = find_by(uid: uid)
        if user and BCrypt::Password.new(user.pass) == pass
            true
        else
            false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])
        tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
 

 def login_form
   render :login
 end


  def login
    if User.autenticate(params[:uid],params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render :error
    end
  end


  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
    user = User.find_by(uid: session[:login_uid])
    @tweet = Tweet.new(message: params[:tweet][:message],user_id:user.id)
    if @tweet.save
      flash[:info] = 'ツイートしました'
      redirect_to tweets_path
    else
      render :new
    end
  end
  
  def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      flash[:info] = '一件削除しました'
      redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    p = BCrypt::Password.create(params[:user][:pass])
    @user = User.new(uid: params[:user][:uid],pass: p)
    if @user.save
      flash[:info] = 'ユーザーを登録しました'
      redirect_to users_path
    else
      @user.pass = ""
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:info] = 'ユーザーを一件削除しました'
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>エラーがあります</h1>

ログイン失敗しました。

<hr>

<p>
    <%= link_to '戻る' , :back %>
</p>

app/views/top/login.html.erb
<h1>ログイン</h1>

<hr>

<%= form_tag '/top/login', method: :post do %>
    <p>
        <%= label_tag :uid, 'ユーザーID' %>
        <%= text_field_tag :uid %>
    </p>
    <p>
        <%= label_tag :pass, 'パスワード' %>
        <%= password_field_tag :pass %>
    </p>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/index.html.erb
<h1>ツイート一覧</h1>

<hr>

<% @tweets.each do |e| %>
<p>
    <%= e.message %>
    <%= User.find(e.user_id).uid %>
    
    <% if e.likes.empty? %>
            <%= link_to '♡', likes_path(tweet_id: e.id) ,method: :post %>
        <% else %>
            <%= link_to '❤︎', like_path(e) ,method: :delete %>
    <% end %>
    
    <%= link_to '削除',tweet_path(e),method: :delete %>
</p>

<% end %>

<% if session[:login_uid] %>
    <%= link_to 'ツイートする',new_tweet_path %>
<% end %>

<% if session[:login_uid] %>
    <%= link_to 'ログアウト',top_logout_path %>
<% else %>
    <%= link_to 'ログイン',top_login_form_path %>
<% end %>

app/views/tweets/new.html.erb
<h1>ツイート</h1>

<% if @tweet.errors.present? %>
  <font color='red'>
    <h3>エラーがあります</h3>
    <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
    </ul>
  </font>

<% end %>

<%= form_for @tweet,url: {action: :create} do |f| %>
<p>
    <%= f.label :message,'つぶやき' %>
    <%= f.text_field :message %>
</p>

<p>
    <%= f.submit 'ツイート' %>
</p>

<%end%>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% if flash[:info] %>
    <font color='green' ><%= flash[:info] %></font>
<% end %>

<% @users.each do |e| %>
    <p>
        <%= e.uid %>
        <%= link_to '削除', user_path(e) , method: :delete %>
    </p>
<% end %>

<hr>

<%= link_to 'ユーザー追加',new_user_path %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<% if @user.errors.present? %>
  <font color='red'>
    <h3>エラーがあります</h3>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
    </ul>
  </font>
<% end %>

<%= form_for @user ,url: {action: :create} do  |f| %>
 <p>
     <%= f.label :uid,'ユーザーID' %>
     <%= f.text_field :uid %>
 </p>
 
 <p>
     <%= f.label :pass,'パスワード' %>
     <%= f.text_field :pass %>
 </p>
 
 <p>
     <%= f.submit '登録' %>
 </p>

 <% end %>